베르실 예약 페이지 리팩토링
Team-INSERT/bssm-frontend pull request #114
Opened 2023-11-16 15:17 UTC by Ubinquitous

## 작업사항
완료!

2023-11-17 03:28 UTC, arkk200 commented on src/components/atoms/Input.tsx
> +  fontSize?: string;
이 속성은 안쓰이고 있는데 추가하신 이유가 있으신가요?

2023-11-17 04:54 UTC, arkk200 requested changes
수고하셨스빈다

2023-11-17 04:54 UTC, arkk200 commented on src/components/atoms/Input.tsx
> +  fontSize?: string;
이 속성은 안쓰이고 있는 것 같은데 추가하신 이유가 있으신가요?

2023-11-17 04:54 UTC, arkk200 commented on src/templates/ber/helpers/getIfReservedRoomCSS.helper.ts
> +      }
css 가상 요소로 글자를 표시하는 이유가 있나요?

2023-11-17 04:54 UTC, arkk200 commented on src/templates/ber/hooks/useBerReserve.ts
> +    handleCreateReserveClick,
깅이 알맞게 딱 맞는게 기분 좋네요

2023-11-18 05:41 UTC, Ubinquitous commented on src/templates/ber/helpers/getIfReservedRoomCSS.helper.ts
> +      }
나타낼 수 있는 status가 예약중, 예약완료, 선택중 총 세 개인데
이를 나타내려면 삼항연산자를 두 번 사용해야하는 경우가 나와서 그 경우보단 가상 요소로 글자를 표시하는게
더욱 깔끔한 방법이라고 생각했습니다!

2023-11-18 05:41 UTC, Ubinquitous commented on src/components/atoms/Input.tsx
> +  fontSize?: string;
쓰려고 넣어놓고 까먹었네요 ㅎㅎ 삭제했습니다!

2023-11-18 05:41 UTC, Ubinquitous commented on src/templates/ber/hooks/useBerReserve.ts
> +    handleCreateReserveClick,
껄껄좋습민다

2023-11-18 08:57 UTC, arkk200 approved these changes

2023-11-18 08:58 UTC, merged