게시판 도메인 리팩토링
Team-INSERT/bssm-frontend pull request #117
Opened 2023-11-19 17:44 UTC by Ubinquitous

살려주세요

2023-11-19 23:09 UTC, arkk200 requested changes

2023-11-19 23:09 UTC, arkk200 commented on src/components/atoms/Button.tsx
>  interface IButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
```suggestion
interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
```

인터페이스 이름 앞에 인터페이스 약자를 붙이는 건 컨벤션인가요?

2023-11-19 23:09 UTC, arkk200 commented on src/app/post/[id]/page.tsx
>  const Post = ({ params }: IPostAppPageParams) => {
이미 post/ 페이지에서 Post라는 이름을 사용하고 있는데 어차피 상관없긴 하지만 이름을 바꾸는게 어떤가요?

```suggestion
 const PostDetail = ({ params }: IPostAppPageParams) => {
```

2023-11-19 23:09 UTC, arkk200 commented on src/apis/httpClient/httpClient.ts
> +import ERROR from "@/constants/error.constant";
constants/index.ts에서 ERROR 객체를 re-export 했는데 이렇게 불러온 이유가 있나요?

2023-11-19 23:09 UTC, arkk200 commented on src/app/not-found.tsx
> +import ROUTER from "@/constants/router.constant";
이 ROUTER도 constants/index.ts에서 재내보내기 했으니 "@/constants" 에서 불러오는게 맞을 것 같습니다
```suggestion
import { ROUTER } from "@/constants";
```

2023-11-19 23:09 UTC, arkk200 commented on src/templates/bamboo/services/query.service.ts
> +import KEY from "@/constants/key.constant";
얘도

```suggestion
import { KEY } from "@/constants";
```

2023-11-19 23:09 UTC, arkk200 commented on src/templates/post/interfaces/comment.interface.ts
> +export default interface Comment {
```suggestion
export default interface Comment {
```
여기는 왜 I를 안붙였나요?

2023-11-20 08:19 UTC, Ubinquitous commented on src/components/atoms/Button.tsx
>  interface IButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
헉 옛날컨벤션이었는데 컨벤션을 바꾸면서 변경이 안되었네요

2023-11-20 08:19 UTC, Ubinquitous commented on src/app/post/[id]/page.tsx
>  const Post = ({ params }: IPostAppPageParams) => {
좋습니다!

2023-11-20 08:21 UTC, Ubinquitous commented on src/apis/httpClient/httpClient.ts
> +import ERROR from "@/constants/error.constant";
index.ts가 중간에 날아가버리는 바람에 import문이 꼬인것같습니다 전체적으로 import볼때 고칠것같습니다!

2023-11-20 08:21 UTC, Ubinquitous commented on src/app/not-found.tsx
> +import ROUTER from "@/constants/router.constant";
위와 같습니다!!

2023-11-20 08:21 UTC, Ubinquitous commented on src/templates/bamboo/services/query.service.ts
> +import KEY from "@/constants/key.constant";
위같!

2023-11-20 08:22 UTC, Ubinquitous commented on src/templates/post/interfaces/comment.interface.ts
> +export default interface Comment {
현컨벤션은 I를 사용하지않습니다!

2023-11-20 08:25 UTC, arkk200 approved these changes
수고하셨습니다.

2023-11-20 08:26 UTC, merged