useUser, useWindow, useModal 훅 선언, Aside에 user api값 연결
Team-INSERT/bssm-frontend pull request #38
Opened 2023-07-20 09:17 UTC by Ubinquitous

## 작업사항
- useUser, useWindow, useModal 훅을 선언했습니다.
- 기존 BSM에서 사용하던 그대로 UserType을 지정했습니다.
-  Aside 컴포넌트에 user api값을 연결했습니다.

## 변경한 점
- 각 페이지 디렉터리 내에 있던 adaptors 디렉터리들을 삭제했습니다. httpClient라는 이름으로 각 adaptors의 index에서 import했을 때, 다른 adaptors에 존재하는 httpClient와 import 경로가 충돌할 수 있어 이를 미연에 방지하고자 adaptors를 사용하지 않고, @/apis/httpClient에 있는 메인 모듈을 사용하기로 결정했습니다.

2023-07-20 12:34 UTC, arkk200 requested changes

2023-07-20 12:34 UTC, arkk200 commented on src/apis/error/throwAxiosError.ts
> +const throwAxiosError = (err: unknown) => {
이 함수가 반환하는 타입이 data 프로퍼티가 포함되어 있는 객체 또는 code 프로퍼티가 포함되어 있는 객체, 이렇게 두 타입으로 되어 있는 것 같은데 이렇게 한 이유가 있으신가요?

2023-07-20 12:34 UTC, arkk200 commented on src/components/atoms/ImageWithFallback.tsx
>        onErrorDelete={onErrorDelete}
onErrorDelete가 boolean 형으로 되어 있는데 불린 네이밍 컨벤션을 참고해서 짖는게 어떨까요?
https://soojin.ro/blog/naming-boolean-variables
참고자료 남겨봅니다

2023-07-20 12:34 UTC, arkk200 commented on src/components/atoms/Select.tsx
> +  size = "80px",
이 size라는 프롭스는 너비 값에만 관여하니깐 width라고 짖는건 어떨까요?
```suggestion
  width = "80px",
```

2023-07-20 12:34 UTC, arkk200 commented on src/components/atoms/Select.tsx
> +  const [hover, setHover] = React.useState(true);
여기도 불린 네이밍 컨벤션에 맞추면 좋을 것 같아요

2023-07-20 12:34 UTC, arkk200 commented on src/hooks/useWindow.ts
> +    if (typeof window !== "undefined") setIsWindow(true);
```suggestion
    setIsWindow(typeof window !== "undefined");
```
이렇게 바꿔도 될 것 같습니다.

2023-07-20 14:39 UTC, J1min commented on src/global/helpers/profileMaker.helper.ts
> +const profileMaker = (userCode: number) => {
개인적으로 이렇게 url을 파싱? 해주는 함수는 getProfileUrl 이런 식으로 이름 짓는걸 선호하는데 helper는 어떤 역할을 하는 친구들을 담아놓은 폴더인가요?

2023-07-20 14:42 UTC, J1min commented on src/page/timetable/assets/DownArrow.tsx
> +      height={height ?? 25}
?? 는 null 병합 연산자라서 아마 undefined로 들어오는 여기선 || 이 더 적절할 것 같습니다~

2023-07-20 14:43 UTC, J1min commented on src/store/user.store.ts
> +    studentNo: -1,
보통 primary key 는 1부터 시작해서 저는 이런 값을 에러 처리하기 편하게 0으로 잡고 하는 편입니다

2023-07-20 14:43 UTC, J1min approved these changes
수고하셨습니다~

2023-07-20 14:59 UTC, J1min commented on src/hooks/useWindow.ts
> +    if (typeof window !== "undefined") setIsWindow(true);
저는 개인적으로 위의 방법이 더 직관적인 것 같습니다
추가적으로 저렇게 작성할 경우, 의도치 않게 state가 변경되어 의도치 않은 재랜더링을 할 수도 있을 것 같습니다~

2023-07-21 04:29 UTC, merged

2023-07-21 04:39 UTC, Ubinquitous commented on src/components/atoms/ImageWithFallback.tsx
>        onErrorDelete={onErrorDelete}
좋은 자료네요 변경 완료했습니다!!

2023-07-21 04:42 UTC, Ubinquitous commented on src/components/atoms/Select.tsx
> +  const [hover, setHover] = React.useState(true);
감사합니다 반영했습니다!

2023-07-21 04:42 UTC, Ubinquitous commented on src/components/atoms/Select.tsx
> +  size = "80px",
좋습니당

2023-07-21 04:44 UTC, Ubinquitous commented on src/global/helpers/profileMaker.helper.ts
> +const profileMaker = (userCode: number) => {
해당 함수도 좋은 것 같습니다 helper는 개발을 진행하며 유용하게 사용되는 짧은 함수들을 모아두는 디렉터리로 사용하고 있습니다
저번 부마위키 개발 때 사용하던 utils 디렉터리와 비슷합니다!

2023-07-21 04:44 UTC, Ubinquitous commented on src/global/helpers/profileMaker.helper.ts
> +const profileMaker = (userCode: number) => {
네이밍 센스가 좀 구려서^^.. 반영완료했습니다!

2023-07-21 04:47 UTC, Ubinquitous commented on src/store/user.store.ts
> +    studentNo: -1,
반영했습니다!

2023-07-21 04:50 UTC, Ubinquitous commented on src/page/timetable/assets/DownArrow.tsx
> +      height={height ?? 25}
반영했습니다ㅏ

2023-07-21 04:51 UTC, Ubinquitous commented on src/apis/error/throwAxiosError.ts
> +const throwAxiosError = (err: unknown) => {
아직은 API를 많이 핸들링하지 않아 예외처리 단계에서 딱히 처리해줄 로직이 없다보니 함수의
뼈대만 있는 상태입니다!! err 타입은 AxiosError 타입으로 받아야할지 애매해서 이렇게 받았습니당